alias cdd='cd;cd Desktop'
alias cs='cd;cd Desktop/workspace/sympy'
alias cds='cd;cd Desktop/sympy'
alias cb='cd;cd Desktop/workspace/myweb/aktech.github.io'
alias cbg='cd;cd Desktop/workspace/myweb/blog-gen/aktech.github.io'

# Git Aliases
alias gs='git status'
alias gl='git log'
alias gd='git diff'
alias gds='git diff --stat'
alias gcom='git commit -m'
alias e='exit'
alias c='clear'
alias ipy='ipython'
alias ipyn='ipython notebook'
alias gb='git branch'
alias gc='git checkout'
alias gcm='git checkout master'
alias gp='git push'
alias ga='git add .'
alias gpum='git pull upstream master'
alias gpom='git push origin master'
alias py='python'
alias py3='python3'
alias wn='winpdb'
alias t='./bin/test'
alias dt='./bin/doctest'
alias cov='bin/coverage_report.py'

alias update_dturm='python appcfg.py -A dturm-1021 update dturm/'
alias run_dturm='python dev_appserver.py dturm/'


alias update_dturm2='python appcfg.py -A dturm2 update dturm2/'
alias run_dturm2='python dev_appserver.py dturm2/'
alias cr='g++ -o t t.cpp;./t;rm t'
